import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
// import { ourFileRouter } from "./api/uploadthing/core";
// import { extractRouterConfig } from "uploadthing/server";
// import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
// import { Toaster } from "react-hot-toast";
// import Providers from "@/components/Providers";
// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import dynamic from "next/dynamic";
import { PHProvider } from "@/components/posthog-provider";
// const PostHogPageView = dynamic(() => import("@/components/PostHogPageView"), {
//   ssr: false,
// });
export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) 
{
  return (
    <html lang="en">
      <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <main>
              {children}
            </main>
          </ThemeProvider>
      </body>
    </html>
  );
}
